### ISSUE TITLE
One-step installation fails if tornado is not installed

### ISSUE THREAD

**Issue by kmike** [mrjoes/tornadio#1]
This is a quite minor issue but it can break automatic deployment in some cases.

```
(myenv)> pip install tornado -e git+git://github.com/MrJoes/tornadio.git#egg=tornadio

Downloading/unpacking tornado
  Running setup.py egg_info for package tornado
    warning: no files found matching '*.png' under directory 'demos'
Obtaining tornadio from git+git://github.com/MrJoes/tornadio.git#egg=tornadio
  Cloning git://github.com/MrJoes/tornadio.git to ./envs/myend/src/tornadio
  Running setup.py egg_info for package tornadio
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/kmike/envs/myenv/src/tornadio/setup.py", line 9, in <module>
        import tornadio
      File "tornadio/__init__.py", line 15, in <module>
        from tornadio.router import get_router
      File "tornadio/router.py", line 13, in <module>
        from tornado import ioloop
    ImportError: No module named tornado
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/kmike/envs/myenv/src/tornadio/setup.py", line 9, in <module>

    import tornadio

  File "tornadio/__init__.py", line 15, in <module>

    from tornadio.router import get_router

  File "tornadio/router.py", line 13, in <module>

    from tornado import ioloop

ImportError: No module named tornado

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /Users/kmike/.pip/pip.log
```

That's obviously because of imports in tornadio/**init**.py and the fact tornado version is defined there.

Pip installs packages only as a last step. It runs 'setup.py egg_info'  before installing so it is not safe to assume tornado is installed in tornadio's setup.py.

I wasn't able to come up with a good fix. The easiest way seems to be to duplicate the version definition. Another possibility is to remove 'shortcuting' imports from **init**.py. I think catching import errors in **init**.py is much worse.

**Comment by mrjoes** [comment]
My bad, missed tornado dependency. For now, I will just duplicate version numbers.
