### ISSUE TITLE
Tornado iostream error with tornadio 

### ISSUE THREAD

**Issue by fabware** [mrjoes/tornadio#16]
randomly found the following error, current socket.io session not respond, heartbeat is ok. It able to accept new socket.io connections.

ERROR:root:Uncaught exception POST /post/98/ (192.168.60.60)
HTTPRequest(protocol='http', host='192.168.60.60:40000', method='POST', uri='/post/98/', version='HTTP/1.1', remote_ip='192.168.60.60', remote_ip='192.168.60.60', body='msg=webgameTips::hello', headers={'Host': '192.168.60.60:40000', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '91', 'Accept': '_/_', 'User-Agent': 'curl/7.19.7 (i486-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k zlib/1.2.3.3 libidn/1.15'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/web.py", line 814, in _stack_context
    yield
  File "/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/stack_context.py", line 77, in StackContext
    yield
  File "/usr/lib/python2.6/contextlib.py", line 113, in nested
    yield vars
  File "/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/stack_context.py", line 126, in wrapped
    callback(_args, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/httpserver.py", line 300, in _on_write_complete
    self._finish_request()
  File "/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/httpserver.py", line 319, in _finish_request
    self.stream.read_until("\r\n\r\n", self._on_headers)
  File "/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/iostream.py", line 99, in read_until
    self._add_io_state(self.io_loop.READ)
  File "/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/iostream.py", line 315, in _add_io_state
    self.io_loop.update_handler(self.socket.fileno(), self._state)
AttributeError: 'NoneType' object has no attribute 'fileno'
ERROR:root:Cannot send error response after headers written

partial code can be found at gist: https://gist.github.com/992750

**Comment by mrjoes** [comment]
Hi,

  It is crashing in Tornado http web request handler, before Tornadio 
takes control. From what I'm seeing, you have to upgrade to latest 
Tornado version (1.2.1 I think).

Serge.

**Comment by fabware** [comment]
Hi, Serge

Thanks for prompt help. I don't see the error anymore for now. Closing this issue.

can
