### ISSUE TITLE
IOErrors with websockets on Tornado 2.1.1

### ISSUE THREAD

**Issue by tmorgan** [mrjoes/tornadio#34]
I get a log full of: 

2011-10-06 15:09:27,355 root     ERROR    Error in periodic callback
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/tornadio/periodic.py", line 42, in _run
    next_call = self.callback()
  File "build/bdist.linux-i686/egg/tornadio/conn.py", line 141, in _heartbeat
    self.close()
  File "build/bdist.linux-i686/egg/tornadio/conn.py", line 85, in close
    self._protocol.close()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/tornado-2.1.1-py2.7.egg/tornado/websocket.py", line 121, in close
    self.ws_connection.close()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/tornado-2.1.1-py2.7.egg/tornado/websocket.py", line 497, in close
    self._write_frame(True, 0x8, b(""))
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/tornado-2.1.1-py2.7.egg/tornado/websocket.py", line 400, in _write_frame
    self.stream.write(frame)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/tornado-2.1.1-py2.7.egg/tornado/iostream.py", line 213, in write
    self._check_closed()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/tornado-2.1.1-py2.7.egg/tornado/iostream.py", line 504, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed

heartbeat not getting cancelled?

**Comment by mrjoes** [comment]
Hi, try using latest Git version and see if it still fails - there was recent fix for this issue.

**Comment by tmorgan** [comment]
Hi, I was already at HEAD yesterday, having seen the psobot/patch-1 commit was related. I also tried rolling tornado back to 2.1, no joy. I added some more debug statements, definitely the heartbeat, but I can't see why it was continuing to fire.

**Comment by peterbe** [comment]
@tmorgan I know it's a trivial suggestion but see if there isn't a traceback before. I usually found that I got those "Stream is closed" **after** another exception has been raised.

**Comment by mrjoes** [comment]
Ahem, maybe it is exception in your code? It throws exception, Tornado
decides to finish request and close socket and tornadio tries to close it
once again because of the close callback.

If it is the case, I might be able to do some workaround for these cases.

Serge.

**Comment by tmorgan** [comment]
There was nothing in the log to indicate and exception in my code..... I've now removed my dependency on tornadio, because I hadn't more time to look into this. I believe it may of been an artefact of the proxying setup on our server as I couldn't reproduce it locally. As such I'm closing the issue. Thanks.
